# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  test:
    docker:
    - image: circleci/golang:1.10
    working_directory: /go/src/github.com/ryutah/osin-datastore
    steps:
    - checkout

    # specify any bash command here prefixed with `run: `
    - run:
        name: Resolve dependencies
        command: cd v1 && dep ensure
    - run:
        name: Test
        command: go test -v ./...

workflows:
  version: 2
  test:
    jobs:
    - test
